export const diningData = [
  {
    itemId: "1",
    itemMainCategory: "Home",
    itemSubCategory: "Dining",
    itemCategory: "Bowls",
    itemName: "Mandarin Begonaia Set of 3 Bone China Printed Bowls - 470ml",
    itemPic: [
      {
        pic1: "",
        pic2: "",
        pic3: "",
        pic4: "",
      },
    ],
    itemMRP: "",
    itemDiscount: "10",
    itemSalesPrice: "",
    itemDescription: "",
    itemWeight: "",
    itemBrand: "",
    itemReviews: ["review1", "review2", "review3"],
    },
    {
        itemId: "2",
        itemMainCategory: "Home",
        itemSubCategory: "Dining",
        itemCategory: "Bowls",
        itemName: "Mandarin Begonaia Set of 3 Bone China Printed Bowls - 470ml",
        itemPic: [
          {
            pic1: "",
            pic2: "",
            pic3: "",
            pic4: "",
          },
        ],
        itemMRP: "",
        itemDiscount: "",
        itemSalesPrice: "",
        itemDescription: "",
        itemWeight: "",
        itemBrand: "",
        itemReviews: ["review1", "review2", "review3"],
    },
    {
        itemId: "3",
        itemMainCategory: "Home",
        itemSubCategory: "Dining",
        itemCategory: "Bowls",
        itemName: "Mandarin Begonaia Set of 3 Bone China Printed Bowls - 470ml",
        itemPic: [
          {
            pic1: "",
            pic2: "",
            pic3: "",
            pic4: "",
          },
        ],
        itemMRP: "",
        itemDiscount: "",
        itemSalesPrice: "",
        itemDescription: "",
        itemWeight: "",
        itemBrand: "",
        itemReviews: ["review1", "review2", "review3"],
    },
    {
        itemId: "4",
        itemMainCategory: "Home",
        itemSubCategory: "Dining",
        itemCategory: "Bowls",
        itemName: "Mandarin Begonaia Set of 3 Bone China Printed Bowls - 470ml",
        itemPic: [
          {
            pic1: "",
            pic2: "",
            pic3: "",
            pic4: "",
          },
        ],
        itemMRP: "",
        itemDiscount: "",
        itemSalesPrice: "",
        itemDescription: "",
        itemWeight: "",
        itemBrand: "",
        itemReviews: ["review1", "review2", "review3"],
    },
    {
        itemId: "5",
        itemMainCategory: "Home",
        itemSubCategory: "Dining",
        itemCategory: "Bowls",
        itemName: "Mandarin Begonaia Set of 3 Bone China Printed Bowls - 470ml",
        itemPic: [
          {
            pic1: "",
            pic2: "",
            pic3: "",
            pic4: "",
          },
        ],
        itemMRP: "",
        itemDiscount: "",
        itemSalesPrice: "",
        itemDescription: "",
        itemWeight: "",
        itemBrand: "",
        itemReviews: ["review1", "review2", "review3"],
      },
];
